---
- !mapping
  action: 2d drag translate
  contexts: [bdv2D]
  triggers: [button2, button3]
- !mapping
  action: 2d rotate left
  contexts: [bdv2D]
  triggers: [LEFT]
- !mapping
  action: 2d zoom in
  contexts: [bdv2D]
  triggers: [UP]
- !mapping
  action: 2d rotate right
  contexts: [bdv2D]
  triggers: [RIGHT]
- !mapping
  action: 2d zoom out
  contexts: [bdv2D]
  triggers: [DOWN]
- !mapping
  action: 2d drag rotate
  contexts: [bdv2D]
  triggers: [button1]
- !mapping
  action: 2d scroll zoom
  contexts: [bdv2D]
  triggers: [meta scroll, shift ctrl scroll]
- !mapping
  action: 2d rotate right slow
  contexts: [bdv2D]
  triggers: [ctrl RIGHT]
- !mapping
  action: 2d zoom out slow
  contexts: [bdv2D]
  triggers: [ctrl DOWN]
- !mapping
  action: 2d zoom out fast
  contexts: [bdv2D]
  triggers: [shift DOWN]
- !mapping
  action: 2d rotate right fast
  contexts: [bdv2D]
  triggers: [shift RIGHT]
- !mapping
  action: 2d scroll rotate slow
  contexts: [bdv2D]
  triggers: [ctrl scroll]
- !mapping
  action: 2d zoom in fast
  contexts: [bdv2D]
  triggers: [shift UP]
- !mapping
  action: 2d rotate left fast
  contexts: [bdv2D]
  triggers: [shift LEFT]
- !mapping
  action: 2d scroll translate
  contexts: [bdv2D]
  triggers: [not mapped]
- !mapping
  action: 2d rotate left slow
  contexts: [bdv2D]
  triggers: [ctrl LEFT]
- !mapping
  action: 2d scroll rotate fast
  contexts: [bdv2D]
  triggers: [shift scroll]
- !mapping
  action: 2d zoom in slow
  contexts: [bdv2D]
  triggers: [ctrl UP]
- !mapping
  action: 2d scroll rotate
  contexts: [bdv2D]
  triggers: [scroll]
- !mapping
  action: drag translate
  contexts: [bdv3D]
  triggers: [button2, button3]
- !mapping
  action: rotate left
  contexts: [bdv3D]
  triggers: [LEFT]
- !mapping
  action: zoom in
  contexts: [bdv3D]
  triggers: [UP]
- !mapping
  action: rotate right
  contexts: [bdv3D]
  triggers: [RIGHT]
- !mapping
  action: zoom out
  contexts: [bdv3D]
  triggers: [DOWN]
- !mapping
  action: forward z
  contexts: [bdv3D]
  triggers: [COMMA]
- !mapping
  action: backward z
  contexts: [bdv3D]
  triggers: [PERIOD]
- !mapping
  action: drag rotate fast
  contexts: [bdv3D]
  triggers: [shift button1]
- !mapping
  action: drag rotate
  contexts: [bdv3D]
  triggers: [button1]
- !mapping
  action: scroll zoom
  contexts: [bdv3D]
  triggers: [meta scroll, shift ctrl scroll]
- !mapping
  action: rotate right slow
  contexts: [bdv3D]
  triggers: [ctrl RIGHT]
- !mapping
  action: zoom out slow
  contexts: [bdv3D]
  triggers: [ctrl DOWN]
- !mapping
  action: backward z slow
  contexts: [bdv3D]
  triggers: [ctrl PERIOD]
- !mapping
  action: forward z slow
  contexts: [bdv3D]
  triggers: [ctrl COMMA]
- !mapping
  action: scroll browse z slow
  contexts: [bdv3D]
  triggers: [ctrl scroll]
- !mapping
  action: axis x
  contexts: [bdv3D]
  triggers: [X]
- !mapping
  action: axis y
  contexts: [bdv3D]
  triggers: [Y]
- !mapping
  action: axis z
  contexts: [bdv3D]
  triggers: [Z]
- !mapping
  action: rotate left slow
  contexts: [bdv3D]
  triggers: [ctrl LEFT]
- !mapping
  action: zoom in slow
  contexts: [bdv3D]
  triggers: [ctrl UP]
- !mapping
  action: scroll browse z
  contexts: [bdv3D]
  triggers: [scroll]
- !mapping
  action: drag rotate slow
  contexts: [bdv3D]
  triggers: [ctrl button1]
- !mapping
  action: forward z fast
  contexts: [bdv3D]
  triggers: [shift COMMA]
- !mapping
  action: backward z fast
  contexts: [bdv3D]
  triggers: [shift PERIOD]
- !mapping
  action: zoom out fast
  contexts: [bdv3D]
  triggers: [shift DOWN]
- !mapping
  action: rotate right fast
  contexts: [bdv3D]
  triggers: [shift RIGHT]
- !mapping
  action: zoom in fast
  contexts: [bdv3D]
  triggers: [shift UP]
- !mapping
  action: rotate left fast
  contexts: [bdv3D]
  triggers: [shift LEFT]
- !mapping
  action: scroll browse z fast
  contexts: [bdv3D]
  triggers: [shift scroll]
